"version: "3"
services:
  users-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: fortysix-ntwo/grpc-api:1.0
    init: true
    env_file:
      - ./.env
    environment:
      - PORT="${PORT}"
    depends_on:
      - postgres
    networks:
      network:
      ipv4_address: 172.20.0.2
    volumes:
      - appdata:/opt/app
    working_dir: /opt/app
    ports:
      - ${PORT}:50052
    restart: always

  postgres:
    image: postgres:12.3-alpine
    init: true
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"
      - PG_PORT="${PG_PORT}"
    networks:
      network:
      ipv4_address: 172.20.0.2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    restart: always

networks:
  network:
    driver: bridge
    ipam:
    config:
      - subnet: 172.20.0.0/16

volumes:
  postgres:
  appdata:
