version: "3"
services:
  users-service:
    build:
      context: ./
      dockerfile: ./Dockerfile.api
    image: fortysix-ntwo/grpc-api:1.0
    env_file:
      - ./.env
    environment:
      - PORT="${PORT}"
    depends_on:
      - postgres
    networks:
      - network
    volumes:
      - appdata:/opt/app
    working_dir: /opt/app
    ports:
      - ${PORT}:50052
    restart: always

  postgres:
    build:
      context: ./
      dockerfile: ./Dockerfile.postgres
    image: postgres:12.3-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"
      - PG_PORT="${PG_PORT}"
    networks:
      - network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    restart: always

networks:
  network:
    driver: bridge

volumes:
  postgres:
  appdata:
